services:
  db:
    image: postgres:17
    container_name: bank_istad_db
    restart: always
    environment:
      POSTGRES_DB: bank_istad_db
      POSTGRES_USER: matra
      POSTGRES_PASSWORD: matra
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - istad-network
  kc-fswd:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: kc-fswd
    depends_on:
      - db
    environment:
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://bank_istad_db:5432/bank_istad_db
      KC_DB_USERNAME: matra
      KC_DB_PASSWORD: matra

      # Admin User
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # Production Settings
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8082:8080"
      - "8443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - istad-network
    command:
      - 'start-dev'

volumes:
  postgres_data:
  keycloak_data:

networks:
  istad-network:
