spring.application.name=spring_boot_2

spring.servlet.multipart.file-size-threshold=10MB

media.server-path=/home/somatra/Documents/media/
media.base-uri=http://localhost:8080/media/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/mb-api

spring.datasource.url=jdbc:postgresql://localhost:5432/mb_api_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=matra
spring.datasource.password=matra

# configure JPA Hibernate DDL
# DDL = Data Definition Language

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# customer username, password
spring.security.user.name=matra
spring.security.user.password=123123
